export const LOCATIONS = [
  { name: '23 DE ENERO', km: 5, price: 3.5 },
  { name: 'ANDRES ELOY BLANCO', km: 1, price: 2 },
  { name: 'ARAGUAMA', km: 2.5, price: 2 },
  { name: 'BASE ARAGUA', km: 3.3, price: 2.5 },
  { name: 'BASE SUCRE', km: 9, price: 5 },
  { name: 'BRISAS DEL LAGO', km: 9, price: 5 },
  { name: 'CAGUA', km: 20, price: 10 },
  { name: 'CALICANTO', km: 5, price: 3.5 },
  { name: 'CAMBURITO', km: 7.5, price: 4 },
  { name: 'CAMPO ALEGRE', km: 2.5, price: 2 },
  { name: 'CANDELARIA', km: 12, price: 6 },
  { name: 'CANTARRANA', km: 7.5, price: 4 },
  { name: 'CAÑA DE AZUCAR', km: 10, price: 5 },
  { name: 'CASONA', km: 8.5, price: 4.5 },
  { name: 'CASTAÑO (HASTA HOTEL PIPO)', km: 12, price: 6 },
  { name: 'CC LAS AMERICAS', km: 4.5, price: 3 },
  { name: 'CENTRO', km: 5, price: 3.5 },
  { name: 'DIGA CENTER', km: 6, price: 4 },
  { name: 'EL LIMON', km: 12, price: 6 },
  { name: 'FARINACHI', km: 5.8, price: 3.5 },
  { name: 'GALERIA PLAZA', km: 4.8, price: 3 },
  { name: 'GLOBAL', km: 3, price: 2 },
  { name: 'GRAN BAZAR', km: 3.5, price: 2.5 },
  { name: 'GUASIMAL', km: 5.6, price: 3.5 },
  { name: 'HYPER JUMBO', km: 3.1, price: 2.5 },
  { name: 'INDEPENDENCIA', km: 3.2, price: 2.5 },
  { name: 'LA ARBOLEDA', km: 5, price: 3.5 },
  { name: 'LA BARRACA', km: 2.5, price: 2 },
  { name: 'LA FLORESTA', km: 5.3, price: 3.5 },
  { name: 'LA SOLEDAD', km: 4.2, price: 3 },
  { name: 'LAS ACACIAS', km: 1.2, price: 2 },
  { name: 'LOA AVIADORES', km: 7.5, price: 4 },
  { name: 'LOS OLIVOS', km: 3.5, price: 2.5 },
  { name: 'LOS SAMANES', km: 2.5, price: 2 },
  { name: 'MACARO', km: 13, price: 7 },
  { name: 'MARACAY PLAZA', km: 1.3, price: 2 },
  { name: 'MARACAYA', km: 1.8, price: 2 },
  { name: 'MATA REDONDA', km: 3, price: 2 },
  { name: 'MONTAÑA FRESCA', km: 6.5, price: 4 },
  { name: 'PALO NEGRO', km: 15, price: 6 },
  { name: 'PARAPARAL', km: 6.5, price: 4 },
  { name: 'PARQUE ARAGUA', km: 3, price: 2 },
  { name: 'PIÑONAL', km: 2.1, price: 2 },
  { name: 'REDVITAL', km: 8.5, price: 4.5 },
  { name: 'SAN CARLOS', km: 2, price: 2 },
  { name: 'SAN JACINTO', km: 5.8, price: 3.5 },
  { name: 'SAN JOSE', km: 1.7, price: 2 },
  { name: 'SAN RAFAEL', km: 1.5, price: 2 },
  { name: 'SAN VICENTE', km: 8, price: 4 },
  { name: 'SANTA CRUZ', km: 18, price: 8 },
  { name: 'SANTA RITA', km: 6, price: 4 },
  { name: 'SANTA ROSA', km: 4, price: 3 },
  { name: 'SOROCAIMA 1', km: 8.5, price: 4.5 },
  { name: 'TERMINAL', km: 1.5, price: 2 },
  { name: 'TURMERO', km: 15, price: 8 },
  { name: 'UNICENTRO', km: 3.2, price: 2.5 },
]

export const PERSONAL_DELIVERIES_LOCATIONS = [
  {
    name: 'C.C Galería Plaza',
    exact_address: 'Feria de Comida, en las mesas al frente de Pollos Arturo',
    schedule: '3:30pm - 4:00pm',
  },
  {
    name: 'Gran Bazar',
    exact_address: 'Entrada Principal, Av. Bolívar.',
    schedule: '4:15pm - 4:25pm (Lunes, miércoles y Sabados)',
  },
  {
    name: 'Parque Aragua',
    exact_address: 'Panadería Marapan',
    schedule: '4:30pm - 4:45pm (Lunes, miércoles y Sabados)',
  },
  {
    name: 'Las Américas',
    exact_address: 'Entrada Principal',
    schedule: '5pm - 5:15pm (Lunes, miércoles y Sabados)',
  },
  {
    name: 'Maracay Plaza',
    exact_address: 'Panadería Maracay Plaza ',
    schedule: '3pm - 3:10pm (Lunes, miércoles y Sabados)',
  },
  {
    name: 'Terminal de Pasajeros',
    exact_address:
      'Entrada de la Avenida Fuerzas Aéreas, donde está Krispy Donuts (antiguo McDonalds)',
    schedule: '5:20pm - 5:30pm (Lunes, miércoles y Sabados)',
  },
  {
    name: 'Los Aviadores',
    exact_address: 'Entrada Pronto ',
    schedule: '6pm - 6:15pm (Lunes, miércoles y Sabados)',
  },
  {
    name: 'Fundación Mendoza (Todos los días)',
    exact_address: 'Entrada Principal',
    schedule: 'Avisar por WhatsApp',
  },
]
